# Affirmations/Simple truths {#affirmations}


This is a copy of my affirmations that I am supposed to repeat every morning. I wrote [a post on my blog](https://www.carlitofluitoideas.com/affirmations-truths/) where I explain my process with affirmations. I was skeptic, so then, I decided to say “*Simple truths*” instead. 

Similar concept, similar results. I guess. 

----

**1. Dailies**

I'm alive, I love life.

I'm breathing. Breathing reminds me that being alive is a miracle.

I drink water. Water gives me life.

I fast. Fasting gives me strength, courage and avoids excesses of dopamine.

I move and stretch. Movement and stretching segregate serotonin in my brain and makes me a great performer. Performing is my job.

I workout. Workout keeps my body fit and functional.

I shower with cold water. Cold water strengthen my immune system.

I meditate. Meditation brings sustainable wellbeing.

I don't masturbate. Masturbation drains my energy, life force, and motivation.

I eat fruit. Fruit is the way of saving my life and my planet. 

I am enough and I deserve more. 

I'm lovable, and I love human beings.

I am sexually attractive. I excite women. I make them feel good about themselves and their bodies. Women enjoy my company. I'm a little bit psychopath when flirting.

**2. Demons**

I don't check social media. 

Checking social media destroys my attention, makes me feel lonely, and ruins my life and potential.

**3. Achievements**

I write for, at least, an hour every day, 6 pages a day. Writing is my way of helping others and saving the planet. Writing is my job.

I don't procrastinate. Procrastination is fear. PROCRASTINATION IS FEAR. 

My mind does what it thinks I want it to. 

I make the familiar (bad habits, tendencies) unfamiliar and the unfamiliar (good habits and tendencies) familiar.

I do what I don't want to do, and I do it first.

I take daily actions.

I don't let in criticism, but I do let in praise. 

I don't over think. I just do.

I finish tasks, books, projects, interactions. I am a finisher.

I impact and influence people's lives. 

**4. Dynamics**

There is hope in humankind, and this planet is going to be a wonderful place.

I don't compete, I cooperate. 

**5. Goals** 

I am unstoppable. I am a communal narcissist. I'm a warrior, I'm a saviour. I'm a Swami, I am a Bodhisattva. 

I'm Carlito Fluito.

I'm saving the planet, and I'm doing it today. 

